environment:
  nodejs_version: "6"

version: 3.0.{build}

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build_script:
- cmd: npm run build

test: off
