/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "ms-rest-js";
import * as Models from "./models";
import * as Mappers from "./models/mappers";
import * as operations from "./operations";
import { ElmahioAPIContext } from "./elmahioAPIContext";

class ElmahioAPI extends ElmahioAPIContext {

  // Operation groups
  deployments: operations.Deployments;
  logs: operations.Logs;
  messages: operations.Messages;

  /**
   * @class
   * Initializes a new instance of the ElmahioAPI class.
   * @constructor
   *
   * @param {string} [baseUri] - The base URI of the service.
   *
   * @param {object} [options] - The parameter options
   *
   * @param {Array} [options.filters] - Filters to be added to the request pipeline
   *
   * @param {object} [options.requestOptions] - The request options. Detailed info can be found at
   * {@link https://github.github.io/fetch/#Request Options doc}
   *
   * @param {boolean} [options.noRetryPolicy] - If set to true, turn off default retry policy
   *
   */
  constructor(credentials: msRest.ServiceClientCredentials, baseUri?: string, options?: msRest.ServiceClientOptions) {
    super(credentials, baseUri, options);
    this.deployments = new operations.Deployments(this);
    this.logs = new operations.Logs(this);
    this.messages = new operations.Messages(this);
  }
}

export { ElmahioAPI, Models as ElmahioAPIModels, Mappers as ElmahioAPIMappers };
